# Generated by Django 6.0.6 on 2026-10-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('user', 'USER')], default='user', max_length=100),
        ),
    ]
