# Generated by Django 6.0.6 on 2026-06-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingBusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_seats', models.IntegerField()),
                ('number_plate', models.IntegerField()),
                ('bus_type', models.CharField(max_length=50)),
            ],
        ),
    ]
