# Generated by Django 6.0.6 on 2026-06-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingbusmodel',
            name='departure_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingbusmodel',
            name='from_location',
            field=models.CharField(default='Kathmandu', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingbusmodel',
            name='to_location',
            field=models.CharField(default='Kathmandu', max_length=200),
            preserve_default=False,
        ),
    ]
