# Generated by Django 6.0.6 on 2026-06-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingbusmodel_departure_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingbusmodel',
            name='available_seats',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='bookingbusmodel',
            name='departure_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingbusmodel',
            name='total_seats',
            field=models.IntegerField(default=40),
        ),
    ]
