# Generated by Django 6.0.6 on 2026-07-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingbusmodel',
            name='available_seats',
        ),
        migrations.AddField(
            model_name='trip',
            name='available_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
