# Generated by Django 6.0.6 on 2026-06-30 01:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='route',
            new_name='from_location',
        ),
        migrations.RemoveField(
            model_name='bookingbusmodel',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='bookingbusmodel',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='bookingbusmodel',
            name='to_location',
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='to_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingbusmodel',
            name='number_plate',
            field=models.CharField(max_length=200),
        ),
    ]
