# Generated by Django 6.0.6 on 2026-07-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_trip_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingbusmodel',
            name='number_plate',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=7),
        ),
    ]
