# Generated by Django 6.0.6 on 2026-07-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_trip_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingbusmodel',
            name='bus_type',
            field=models.CharField(choices=[('AC', 'A/C'), ('Non_AC', 'Non-AC'), ('DELUXE', 'Deluxe'), ('SLEEPER', 'Sleeper')], default='Non_AC', max_length=50),
        ),
    ]
