# Generated by Django 6.0.6 on 2026-07-25 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_bookingbusmodel_bus_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='departure_time',
        ),
    ]
