# Generated by Django 6.0.6 on 2026-07-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_remove_trip_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingbusmodel',
            name='bus_type',
            field=models.CharField(choices=[('AC', 'A/C'), ('NON_AC', 'Non-AC'), ('DELUXE', 'Deluxe'), ('SLEEPER', 'Sleeper')], default='NON_AC', max_length=50),
        ),
    ]
